image: jersou/alpine-bash-curl-fx-git-nodejs-unzip

variables:
  GIT_DEPTH: 10000

SERVICE-A:
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: service-A LIB-1/test.sh LIB-2 .gitlab-ci.yml skip.js
  script:
    - ./skip.js || service-A/test.sh
    - ./skip.js || service-A/test.sh
    - ./skip.js || service-A/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-B:
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: service-B LIB-2 .gitlab-ci.yml skip.js
  script:
    - ./skip.js || service-B/test.sh
    - ./skip.js || service-B/test.sh
    - ./skip.js || service-B/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-C:
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: service-C .gitlab-ci.yml skip.js
  script:
    - ./skip.js || service-C/test.sh
    - ./skip.js || service-C/test.sh
    - ./skip.js || service-C/test.sh
