
image: alpine

.check-ci-history:
  stage: test
  # allow the 222 exit code : allow failure if tree is found in history
  allow_failure:
    exit_codes:
      - 222
  before_script:
    - apk --update add git # FIXME: use docker image with git & sh
    # skip the job if not manual and if the SHA-1 of the "$TREE_TO_CHECK" tree is in history
    - |
      [ "$CI_JOB_MANUAL" = true ] \
      || ! grep "^$(git ls-tree HEAD -- $TREE_TO_CHECK | git mktree):" .ci_ok_history \
      || exit 222
  after_script:
    # if job is successful, add the SHA-1 of the "$TREE_TO_CHECK" tree to the history file
    - |
      [ "$CI_JOB_STATUS" = success ] \
       && echo $(git ls-tree HEAD -- $TREE_TO_CHECK | git mktree):${CI_JOB_ID} >> .ci_ok_history
  cache:
    key: "${CI_PROJECT_NAMESPACE}__${CI_PROJECT_NAME}__${CI_JOB_NAME}__ci_ok_history"
    policy: pull-push
    untracked: true
    paths:
      - .ci_ok_history

SERVICE-A:
  extends: .check-ci-history
  variables:
    TREE_TO_CHECK: SERVICE-A/ LIB-1/ LIB-2/ .gitlab-ci.yml
  script:
    - service-A/test.sh

SERVICE-B:
  extends: .check-ci-history
  variables:
    TREE_TO_CHECK: SERVICE-B/ LIB-2/ .gitlab-ci.yml
  script:
    - service-B/test.sh

SERVICE-C:
  extends: .check-ci-history
  variables:
    TREE_TO_CHECK: SERVICE-C/ .gitlab-ci.yml
  script:
    - service-C/test.sh
