image: jersou/alpine-bash-curl-fx-git-nodejs-unzip

SERVICE-A:
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: service-A LIB-1 LIB-2 # .gitlab-ci.yml
  script:
    - ./skip.sh || service-A/test.sh
    - ./skip.sh || service-A/test.sh
    - ./skip.sh || service-A/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-B:
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: service-B LIB-2 # .gitlab-ci.yml
  script:
    - ./skip.sh || service-B/test.sh
    - ./skip.sh || service-B/test.sh
    - ./skip.sh || service-B/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-C:
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: service-C # .gitlab-ci.yml
  script:
    - ./skip.sh || service-C/test.sh
    - ./skip.sh || service-C/test.sh
    - ./skip.sh || service-C/test.sh
