image: jersou/alpine-bash-curl-fx-git-nodejs

.check-ci-history:
  stage: test
  # allow the 222 exit code : allow failure if tree is found in history
  allow_failure:
    exit_codes:
      - 222
  before_script:
    # skip the job if the SHA-1 of the "$TREE_TO_CHECK" tree is in the history
    - "! ./check-ok-in-past.sh $TREE_TO_CHECK || exit 222"

SERVICE-A:
  extends: .check-ci-history
  variables:
    TREE_TO_CHECK: service-A LIB-1 LIB-2 # .gitlab-ci.yml
  script:
    - service-A/test.sh

SERVICE-B:
  extends: .check-ci-history
  variables:
    TREE_TO_CHECK: service-B LIB-2 # .gitlab-ci.yml
  script:
    - service-B/test.sh

SERVICE-C:
  extends: .check-ci-history
  variables:
    TREE_TO_CHECK: service-C # .gitlab-ci.yml
  script:
    - service-C/test.sh
